// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDs4B0H_ZuqTo55eVWGc3d8qav9RJRpNv0',
    appId: '1:702875449663:web:91b13775a2cc014f717b8a',
    messagingSenderId: '702875449663',
    projectId: 'flutterapp-e2d17',
    authDomain: 'flutterapp-e2d17.firebaseapp.com',
    storageBucket: 'flutterapp-e2d17.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcSVRvcUQAHW14itTYWUDpQAgUTUcrTb8',
    appId: '1:702875449663:android:f6fd609d37a47f70717b8a',
    messagingSenderId: '702875449663',
    projectId: 'flutterapp-e2d17',
    storageBucket: 'flutterapp-e2d17.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAn1vbG04LLU0oQvlymBxOQxtwiG1tlcNk',
    appId: '1:702875449663:ios:9ef4276c5ad8fb26717b8a',
    messagingSenderId: '702875449663',
    projectId: 'flutterapp-e2d17',
    storageBucket: 'flutterapp-e2d17.appspot.com',
    iosClientId: '702875449663-5kgb13mnrci14ov58i4no1k47utttrps.apps.googleusercontent.com',
    iosBundleId: 'com.example.appdev',
  );
}
